version: '3.8'

services:
  model_server:
    build:
      context: Engine/
      dockerfile: Model.Dockerfile
    image: ts-echo-model
    container_name: ts-echo-model-cont
    networks:
      - echo-net
    ports:
      - "8501:8501"
    volumes:
      - credentials_volume:/root/.config/gcloud/
    stdin_open: false
    tty: true

  echo_engine:
    build:
      context: Engine/
      dockerfile: Engine.Dockerfile
    image: ts-echo-engine
    container_name: ts-echo-engine-cont
    networks:
      - echo-net
    volumes:
      - credentials_volume:/root/.config/gcloud/
    stdin_open: true
    tty: true

  echo_mqtt:
    build:
      context: MQTT-Server/
      dockerfile: MQTT.Dockerfile
    image: ts-mqtt-server
    container_name: ts-mqtt-server-cont
    networks:
      - echo-net
    stdin_open: false
    tty: true
    ports:
      - "1883:1883"
      - "8000:8000"
      - "8080:8080"

  echo_simulator:
    build:
      context: Simulator/
      dockerfile: Simulator.Dockerfile
    image: ts-simulator
    container_name: ts-simulator-cont
    networks:
      - echo-net
    volumes:
      - credentials_volume:/root/.config/gcloud/
    stdin_open: false
    tty: true

networks:
  echo-net:
    driver: bridge

volumes:
  credentials_volume:
