version: "3.8"

services:
  echo_onset:
      build:
        context: OnsetDetection/
        dockerfile: OnsetDetection.Dockerfile
      image: ts-echo-onset
      container_name: ts-onset-cont
      networks:
        - echo-net_echo-net
      volumes:
        - echo-net_credentials_volume:/root/.config/gcloud/
        - echo-net_recordings:/mnt/recordings
      stdin_open: true
      tty: true

networks:
  echo-net_echo-net:
    external: true

volumes:
  echo-net_credentials_volume:
    external: true
  echo-net_recordings:
    external: true   