version: "3.8"

services:
  echo_engine:
    build:
      context: Engine/
      dockerfile: Engine.Dockerfile
    image: ts-echo-engine
    container_name: ts-echo-engine-cont
    networks:
      - echo-net_echo-net
    volumes:
      - echo-net_credentials_volume:/root/.config/gcloud/
    stdin_open: true
    tty: true

networks:
  echo-net_echo-net:
    external: true

volumes:
  echo-net_credentials_volume:
    external: true