name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd src/Components
        docker-compose build
    - name: Start containers
      run: |
        cd src/Components
        docker-compose up
    - name: Check running containers
      run: |
        cd src/Components
        docker-compose ps
    - name: Stop and remove containers
      run: |
        cd src/Components
        docker-compose down
