name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/Components/**/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/Components/**/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
      
    - uses: actions/checkout@v3

    - name: Check out Docker files from main
      run: |
        git fetch origin main
        git checkout origin/main -- .github/workflows/docker-image.yml

    # New step: Install Docker Compose
    # This step ensures Docker Compose is installed on the runner since it's not available by default.
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    # Modified: Using docker-compose instead of docker compose
    # Replaced `docker compose` with `docker-compose` to match the installation method.
    - name: Build containers
      run: |
        cd src/Components
        docker-compose build
        
    # Modified: Using docker-compose instead of docker compose
    # Replaced `docker compose` with `docker-compose` to match the installation method.
    - name: Start containers
      run: |
        cd src/Components
        docker-compose up -d
    
    - name: Wait for containers to be ready
      run: sleep 180
      
    # Modified: Using docker-compose instead of docker compose
    # Replaced `docker compose` with `docker-compose` to match the installation method.
    - name: Check running containers
      run: |
        cd src/Components
        RUNNING_CONTAINERS=$(docker-compose ps | grep 'Up' | wc -l)
        if [ "$RUNNING_CONTAINERS" -eq 9 ]; then
          echo "All containers are up and running."
        else
          echo "Expected 9 running containers, but found $RUNNING_CONTAINERS. Failing."
          exit 1
        fi
  
    # Modified: Using docker-compose instead of docker compose
    # Replaced `docker compose` with `docker-compose` to match the installation method.
    - name: Stop and remove containers
      run: |
        cd src/Components
        docker-compose down
